v3.5 compatability updates
workarea-commerce/workarea-product_badges pull request #1
Opened 2019-11-11 18:07 UTC by jyucis

no changelog

PRODUCTBADGES-1

2019-11-11 20:02 UTC, tubbo commented on Gemfile
> +# Declare your gem's dependencies in zendesk.gemspec.
wrong gemspec name?

2019-11-11 20:03 UTC, tubbo approved these changes

2019-11-12 14:04 UTC, bencrouse commented on workarea-product_badges.gemspec
> +  s.add_dependency "workarea", "~> 3.x"
So by changing this, we're saying it's compatible with all v3 versions - do we know that's true?

2019-11-14 14:40 UTC, bencrouse requested changes

2019-11-14 14:40 UTC, bencrouse commented on workarea-product_badges.gemspec
> +  s.add_dependency "workarea", ">= 3.x"
So changing this means it's compatible for all Workarea greater than v3, previously it was all Workarea greater than v3.4. Doesn't seem like the change we want?

2019-11-15 14:46 UTC, bencrouse approved these changes

2019-11-15 14:46 UTC, merged